name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Tag Name
        id: tagName
        uses: olegtarasov/get-tag@v2.1.1
      - name: Get Release
        env:
          TAG_NAME: ${{ steps.tagName.outputs.tag }}
        run: |
          touch RELEASE.md
          PREVIOUS_TAG="$(git tag -l --sort=-version:refname | head -2 | tail -1)"
          [[ $PREVIOUS_TAG = $TAG_NAME ]] && PREVIOUS_TAG="$(git log --reverse --pretty='%h' | head -1)"
          printf "%s" "**PyPi Release**: https://pypi.org/project/${GITHUB_REPOSITORY#*/}/${TAG_NAME#v}" >> RELEASE.md
          printf "\n%s" "**Full Changelog**: https://github.com/$GITHUB_REPOSITORY/compare/$PREVIOUS_TAG...$TAG_NAME" >> RELEASE.md
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagName.outputs.tag }}
          release_name: ${{ steps.tagName.outputs.tag }}
          body_path: RELEASE.md